version: "3.8"

services:
  api:
    build:
      context: ./api
      args:
        WITHOUT_RAILS_ENV: $WITHOUT_RAILS_ENV
        JOBS_NUMBER: $JOBS_NUMBER
        WORKDIR: $WORKDIR
    command: ash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      API_DOMAIN: "localhost:$FRONT_PORT"
      MYSQL_USER_NAME: $MYSQL_USER_NAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      RAILS_ENV: $RAILS_ENV
    volumes:
      # [Docker for Mac が遅い(怒) - 箱のプログラミング日記。](https://www.y-hakopro.com/entry/2021/07/11/175236#:~:text=%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%8D%E3%81%9F%E3%80%82-,delegeted%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E4%BD%BF%E7%94%A8,-%E8%AA%BF%E3%81%B9%E3%81%9F%E3%81%A8%E3%81%93%E3%82%8D)
      - "./api:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0.27
    environment:
      TZ: UTC
      MYSQL_USER_NAME: $MYSQL_USER_NAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "4306:3306"
    volumes:
      - "./containers/mysql/conf.d:/etc/mysql/conf.d"
      - "medcool-mysql-data:/var/lib/mysql"

  front:
    build:
      context: ./front
      args:
        API_URL: "http://localhost:$API_PORT"
        CONTAINER_PORT: $CONTAINER_PORT
        WORKDIR: $WORKDIR
    command: yarn dev
    volumes:
      - "./front:/$WORKDIR"
      # [dockerでyarn addすると遅い問題を改善する - Qiita](https://qiita.com/MoguraStore/items/432be06fb333d6158eb1#%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%E3%81%AE%E6%8C%87%E5%AE%9A%E6%96%B9%E6%B3%95)
      - "yarn-cache:/usr/local/share/.cache/yarn/v2"
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api

volumes:
  medcool-mysql-data:
    driver: local
  yarn-cache:
    driver: local
