inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: true
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
    - .git/**/*
  NewCops: enable
  # TargetRailsVersion: ~

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Lint:
  Enabled: true

Metrics:
  Enabled: true

Naming:
  Enabled: true

Performance:
  Enabled: true

Rails:
  Enabled: true

RSpec:
  Enabled: true

Security:
  Enabled: true

Style:
  Enabled: true


# Excluded Files
# Layout/EmptyLines:
#   Exclude:
#     - 'config/environments/development.rb'

# Layout/EmptyLinesAroundBlockBody:
#   Exclude:
#     - 'db/schema.rb'

# Layout/ExtraSpacing:
#   Exclude:
#     - 'config/environments/production.rb'

# Layout/SpaceAroundOperators:
#   Exclude:
#     - 'config/environments/production.rb'

# Layout/SpaceInsideArrayLiteralBrackets:
#   Exclude:
#     - 'config/environments/production.rb'

# Layout/SpaceInsidePercentLiteralDelimiters:
#   Exclude:
#     - 'Gemfile'

# Naming/PredicateName:
#   Exclude:
#     - 'spec/**/*'

# Rails/ContentTag:
#   Exclude:
#     - app/models/**/*.rb

# Rails/CreateTableWithTimestamps:
#   Exclude:
#     - db/migrate/*_create_active_storage_tables.active_storage.rb

# Rails/EnvironmentVariableAccess:
#   Exclude:
#     - lib/**/*.rake

# Rails/Exit:
#   Exclude:
#     - lib/**/*.rake

# Rails/RakeEnvironment:
#   Exclude:
#     - 'lib/capistrano/tasks/**/*.rake'

# Rails/TimeZone:
#   Exclude:
#     - '**/*.gemspec'

# RSpec/BeforeAfterAll:
#   Exclude:
#     - spec/spec_helper.rb
#     - spec/rails_helper.rb
#     - spec/support/**/*.rb

# RSpec/DescribeClass:
#   Description: Check that the first argument to the top-level describe is a constant.
#   Enabled: true
#   Exclude:
#     - "**/spec/features/**/*"
#     - "**/spec/requests/**/*"
#     - "**/spec/routing/**/*"
#     - "**/spec/system/**/*"
#     - "**/spec/views/**/*"

# RSpec/ExpectActual:
#   Exclude:
#     - spec/routing/**/*

# Style/ClassAndModuleChildren:
#   Exclude:
#     - 'test/channels/application_cable/connection_test.rb'
#     - 'test/test_helper.rb'

# Style/Documentation:
#   Exclude:
#     - 'spec/**/*'
#     - 'test/**/*'
#     - 'config/application.rb'

# Style/DocumentationMethod:
#   Exclude:
#     - 'spec/**/*'
#     - 'test/**/*'

# Style/GlobalStdStream:
#   Exclude:
#     - 'config/environments/production.rb'

# Style/IpAddresses:
#   Exclude:
#     - '**/*.gemfile'
#     - '**/Gemfile'
#     - '**/gems.rb'
#     - '**/*.gemspec'

# Style/NumericPredicate:
#   Exclude:
#     - 'spec/**/*'

# Style/RedundantFetchBlock:
#   Exclude:
#     - 'config/puma.rb'
