inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRailsVersion: 3.0.3
  # DisabledByDefault: true
  NewCops: enable
  Exclude:
    - db/schema.rb
    - Gemfile.lock
    - node_modules/**/*
    - test/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
  # TargetRailsVersion: ~

# Bundler:
#   Enabled: true

# Gemspec:
#   Enabled: true

# Layout:
#   Enabled: true

# Lint:
#   Enabled: true

# Metrics:
#   Enabled: true
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
# Naming:
#   Enabled: true

# Performance:
#   Enabled: true

# Rails:
#   Enabled: true

# RSpec:
#   Enabled: true

# Security:
#   Enabled: true

# Style:
#   Enabled: true

# Style/ClassAndModuleChildren:
#   EnforcedStyle: "compact"
#   # Exclude:
#   #   - 'app/controllers/**/*.rb'
# # Excluded Files
# # Layout/EmptyLines:
# #   Exclude:
# #     - 'config/environments/development.rb'

# # Layout/EmptyLinesAroundBlockBody:
# #   Exclude:
# #     - 'db/schema.rb'

# # Layout/ExtraSpacing:
# #   Exclude:
# #     - 'config/environments/production.rb'

# # Layout/SpaceAroundOperators:
# #   Exclude:
# #     - 'config/environments/production.rb'

# # Layout/SpaceInsideArrayLiteralBrackets:
# #   Exclude:
# #     - 'config/environments/production.rb'

# # Layout/SpaceInsidePercentLiteralDelimiters:
# #   Exclude:
# #     - 'Gemfile'

# # Lint/Syntax は false, Exclude の対象にしてはいけない
# # doc: https://docs.rubocop.org/rubocop/configuration.html#:~:text=non%2Dzero%20value.-,There%20is%20one%20exception%20from%20the%20general%20rule%20above%20and%20that%20is%20Lint/Syntax,-%2C%20a%20special%20cop
# # Lint/Syntax:
# #   Exclude:
# #     - 'Gemfile.lock'

Naming/FileName:
  Exclude:
    - Rakefile

Rails/BulkChangeTable:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
#   # Exclude:
# #     - 'spec/**/*'
# #     - 'test/**/*'
# # - 'config/application.rb'

# 以下URLを参考に設定
# https://teratail.com/questions/74592
Style/FrozenStringLiteralComment:
  Exclude:
    - config/**/*
    - db/migrate/*
    - spec/**/*

Style/GlobalStdStream:
  # Enabled: false
  Exclude:
    - config/environments/production.rb

Style/RedundantFetchBlock:
  Enabled: false
